"""empty message

Revision ID: 48097b6016ca
Revises: 4a6b9ed60aaa
Create Date: 2019-10-09 23:55:52.470691

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '48097b6016ca'
down_revision = '4a6b9ed60aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("users", sa.Column("admin", sa.Boolean(), nullable=True))
    # op.execute("UPDATE users SET admin=False")
    # op.alter_column("users", "admin", nullable=False)
    op.add_column(
        'users', 
        sa.Column('password', sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
