FROM python:3.7.4-slim

RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint-stage.sh /usr/src/app/entrypoint-stage.sh
RUN chmod +x /usr/src/app/entrypoint-stage.sh

COPY . /usr/src/app

CMD ["./entrypoint-stage.sh"]